In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data1.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
df = df[df["IMDb"]>6.0]

In [5]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [6]:
df.to_csv("data_updated.csv",index=False)

In [16]:
df1 = pd.read_json("my.json")

In [17]:
df1

   ID   Name                                Address
0   1  Alice   {'city': 'Delhi', 'zipcode': 110001}
1   2    Bob  {'city': 'Mumbai', 'zipcode': 400001}

In [18]:
df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 0 to 11
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Actor                 9 non-null      str
 1   Film                  9 non-null      str
 2   Year                  9 non-null      int64
 3   Genre                 9 non-null      str
 4   BoxOffice(INR Crore)  9 non-null      int64
 5   IMDb                  9 non-null      float64
dtypes: float64(1), int64(2), str(3)
memory usage: 504.0 bytes

In [23]:
data = [
    {"ID":1,"Name":"Alice","Address":{"city":"Delhi","zipcode":110001}},
    {"ID":2,"Name":"Bob","Address":{"city":"Mumbai","zipcode":400001    }}
]

In [24]:
df1= pd.json_normalize(data)

In [25]:
df1

   ID   Name Address.city  Address.zipcode
0   1  Alice        Delhi           110001
1   2    Bob       Mumbai           400001

In [22]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               2 non-null      int64
 1   Name             2 non-null      str
 2   Address.city     2 non-null      str
 3   Address.zipcode  2 non-null      int64
dtypes: int64(2), str(2)
memory usage: 196.0 bytes