In [2]:
import pandas as pd

In [3]:
employees = pd.DataFrame({
    "Emp ID":[1,2,3],
    "Name" : ["Alice","Bob","Charlie"],
    "DeptID" : [10,20,30]
})

departments = pd.DataFrame({
    "DeptID" : [10,20,40],
    "DeptName" : ["HR","Engineering","Marketing"]
})

In [4]:
employees

   Emp ID     Name  DeptID
0       1    Alice      10
1       2      Bob      20
2       3  Charlie      30

In [5]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [6]:
pd.merge(employees,departments,on="DeptID")

   Emp ID   Name  DeptID     DeptName
0       1  Alice      10           HR
1       2    Bob      20  Engineering

In [7]:
pd.merge(employees,departments,on="DeptID",how="left")

   Emp ID     Name  DeptID     DeptName
0       1    Alice      10           HR
1       2      Bob      20  Engineering
2       3  Charlie      30          NaN

In [8]:
pd.merge(employees,departments,on="DeptID",how="right")

   Emp ID   Name  DeptID     DeptName
0     1.0  Alice      10           HR
1     2.0    Bob      20  Engineering
2     NaN    NaN      40    Marketing

In [9]:
pd.merge(employees,departments,on="DeptID",how="outer")

   Emp ID     Name  DeptID     DeptName
0     1.0    Alice      10           HR
1     2.0      Bob      20  Engineering
2     3.0  Charlie      30          NaN
3     NaN      NaN      40    Marketing

CONCATENATING DATAFRAMES

In [17]:
df1 = pd.DataFrame({"Name":["Alice","Bob"],"Score":[423,345]})
df2 = pd.DataFrame({"Name":["Charlie","David"],"Age":[23,45]})

In [18]:
df1

    Name  Score
0  Alice    423
1    Bob    345

In [19]:
df2

      Name  Age
0  Charlie   23
1    David   45

In [20]:
pd.concat([df1,df2])

      Name  Score   Age
0    Alice  423.0   NaN
1      Bob  345.0   NaN
0  Charlie    NaN  23.0
1    David    NaN  45.0

In [21]:
pd.concat([df1,df2],axis=1)

    Name  Score     Name  Age
0  Alice    423  Charlie   23
1    Bob    345    David   45